import React from "react";

// Redux

import { store } from "../store";
import { Provider } from "react-redux";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import ResponsiveAppbar from "../components/ResponsiveAppBar";

// Theming
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

import { useSelector } from "react-redux";
import { RootState } from "../store";
import { Box } from "@mui/material";
import { IntlProvider } from "react-intl";
import AlertProvider from "./components/Alert";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const lightMode = useSelector((root: RootState) => root.app.light_mode);

  // const darkTheme = createTheme({
  //   palette: {
  //     // mode: lightMode,
  //     background: {
  //       default: "#ececec",
  //     },
  //   },
  // });

  return (
    <html lang="en">
      <body>
        <React.StrictMode>
          {/* <Provider store={store}> */}
          {/* <ThemeProvider theme={darkTheme}> */}
          {/* <CssBaseline /> */}

          {/* <IntlProvider
              // messages={messagesInFrench}
              locale="fr"
              defaultLocale="en"
            > */}
          {/* <AlertProvider> */}
          <ResponsiveAppbar />
          <Box sx={{ mt: 8 }}>{children}</Box>
          {/* </AlertProvider> */}
          {/* </IntlProvider> */}
          {/* </ThemeProvider> */}

          {/* <App /> */}
          {/* </Provider> */}
        </React.StrictMode>

     
      </body>
    </html>
  );
}
